#!/usr/bin/env bash
# Install ROG Deck for the current user. Idempotent - safe to rerun.
#
# Nothing here needs root: the service runs as you, reads sysfs, and delegates
# every privileged write to asusd via asusctl.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
UNIT_DIR="$HOME/.config/systemd/user"
APP_DIR="$HOME/.local/share/applications"
SERVICE="rog-deck.service"

echo "==> Checking dependencies"
missing=()
command -v python3 >/dev/null || missing+=("python (python3)")
command -v asusctl >/dev/null || missing+=("asusctl")
if [ "${#missing[@]}" -gt 0 ]; then
  echo "    Missing: ${missing[*]}"
  echo "    Install with: sudo pacman -S --needed asusctl python"
  exit 1
fi
echo "    python3  $(python3 --version 2>&1 | awk '{print $2}')"
echo "    asusctl  $(asusctl info 2>/dev/null | awk '/Software version/{print $3}')"

if ! systemctl is-active --quiet asusd; then
  echo "!!  asusd is not running. Every write will fail until it is:"
  echo "      sudo systemctl enable --now asusd"
fi

command -v supergfxctl >/dev/null || \
  echo "--  supergfxctl absent: GPU mode switching will be hidden (optional)"

echo "==> Installing launcher into $BIN_DIR"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/rog-deck" <<LAUNCHER
#!/usr/bin/env bash
# Generated by rog-deck/install.sh
cd "$REPO_DIR" && exec /usr/bin/python3 -m rog_deck "\$@"
LAUNCHER
chmod +x "$BIN_DIR/rog-deck"

cat > "$BIN_DIR/rog-deck-ripple" <<LAUNCHER
#!/usr/bin/env bash
# Generated by rog-deck/install.sh
cd "$REPO_DIR" && exec /usr/bin/python3 -m rog_deck.ripple "\$@"
LAUNCHER
chmod +x "$BIN_DIR/rog-deck-ripple"

echo "==> Installing user service"
mkdir -p "$UNIT_DIR"
sed "s|@INSTALL_DIR@|$REPO_DIR|g" "$REPO_DIR/packaging/$SERVICE" > "$UNIT_DIR/$SERVICE"

echo "==> Installing the ripple unit (NOT enabled)"
# Deliberately installed-but-disabled: the ripple effect reads key events to
# know which key a wave starts from, which is the user's call to opt into.
sed "s|@INSTALL_DIR@|$REPO_DIR|g" "$REPO_DIR/packaging/rog-deck-ripple.service" \
  > "$UNIT_DIR/rog-deck-ripple.service"

echo "==> Installing desktop entry"
mkdir -p "$APP_DIR"
install -m644 "$REPO_DIR/packaging/rog-deck.desktop" "$APP_DIR/rog-deck.desktop"
command -v update-desktop-database >/dev/null && update-desktop-database "$APP_DIR" 2>/dev/null || true

echo "==> Enabling service"
systemctl --user daemon-reload
systemctl --user enable --now "$SERVICE"
sleep 2

if systemctl --user is-active --quiet "$SERVICE"; then
  echo
  echo "ROG Deck is running -> http://127.0.0.1:8737"
  echo "  logs:    journalctl --user -u $SERVICE -f"
  echo "  stop:    systemctl --user stop $SERVICE"
  echo "  cli:     rog-deck --help   (if ~/.local/bin is on your PATH)"
  echo
  echo "Optional, OFF by default - the reactive keyboard ripple. It reads key"
  echo "events to know where each wave starts; enable it only if that is fine:"
  echo "  rog-deck-ripple                                  # try it in the foreground"
  echo "  systemctl --user enable --now rog-deck-ripple    # run it always"
else
  echo
  echo "Service failed to start. Recent log:"
  journalctl --user -u "$SERVICE" -n 20 --no-pager || true
  exit 1
fi
